services:
  backend:
    build: .
    container_name: python-backend
    volumes:
      - feedback_data:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8181:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  feedback_data:

networks:
  app-network:
    driver: bridge